/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonVariant } from "./components/app-button/app-button";
import { SpinnerSize } from "./components/loading-spinner/loading-spinner";
import { MealPlanEvent } from "./components/meal-plan-card/meal-plan-card";
import { RecipeCardEvent } from "./components/recipe-card/recipe-card";
export { ButtonVariant } from "./components/app-button/app-button";
export { SpinnerSize } from "./components/loading-spinner/loading-spinner";
export { MealPlanEvent } from "./components/meal-plan-card/meal-plan-card";
export { RecipeCardEvent } from "./components/recipe-card/recipe-card";
export namespace Components {
    interface AppButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "loading": boolean;
        /**
          * @default 'primary'
         */
        "variant": ButtonVariant;
    }
    interface LoadingSpinner {
        /**
          * @default 'medium'
         */
        "size": SpinnerSize;
    }
    interface MealPlanCard {
        /**
          * @default ''
         */
        "day": string;
        /**
          * @default ''
         */
        "recipeImage": string;
        /**
          * @default ''
         */
        "recipeTitle": string;
    }
    interface RecipeCard {
        /**
          * @default ''
         */
        "area": string;
        /**
          * @default ''
         */
        "category": string;
        /**
          * @default ''
         */
        "image": string;
        /**
          * @default false
         */
        "isFavorite": boolean;
        /**
          * Identifier returned with card events.
          * @default ''
         */
        "recipeId": string;
        /**
          * Public HTML attribute remains `title`; the internal name avoids HTMLElement.title collisions.
          * @default ''
         */
        "recipeTitle": string;
    }
    interface SearchBar {
        /**
          * @default 'Search recipes'
         */
        "placeholder": string;
        /**
          * @default ''
         */
        "value": string;
    }
}
export interface MealPlanCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMealPlanCardElement;
}
export interface RecipeCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeCardElement;
}
export interface SearchBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSearchBarElement;
}
declare global {
    interface HTMLAppButtonElement extends Components.AppButton, HTMLStencilElement {
    }
    var HTMLAppButtonElement: {
        prototype: HTMLAppButtonElement;
        new (): HTMLAppButtonElement;
    };
    interface HTMLLoadingSpinnerElement extends Components.LoadingSpinner, HTMLStencilElement {
    }
    var HTMLLoadingSpinnerElement: {
        prototype: HTMLLoadingSpinnerElement;
        new (): HTMLLoadingSpinnerElement;
    };
    interface HTMLMealPlanCardElementEventMap {
        "editMeal": MealPlanEvent;
        "removeMeal": MealPlanEvent;
        "viewMeal": MealPlanEvent;
    }
    interface HTMLMealPlanCardElement extends Components.MealPlanCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMealPlanCardElementEventMap>(type: K, listener: (this: HTMLMealPlanCardElement, ev: MealPlanCardCustomEvent<HTMLMealPlanCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMealPlanCardElementEventMap>(type: K, listener: (this: HTMLMealPlanCardElement, ev: MealPlanCardCustomEvent<HTMLMealPlanCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMealPlanCardElement: {
        prototype: HTMLMealPlanCardElement;
        new (): HTMLMealPlanCardElement;
    };
    interface HTMLRecipeCardElementEventMap {
        "recipeSelected": RecipeCardEvent;
        "favoriteToggled": RecipeCardEvent & { isFavorite: boolean };
    }
    interface HTMLRecipeCardElement extends Components.RecipeCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeCardElement: {
        prototype: HTMLRecipeCardElement;
        new (): HTMLRecipeCardElement;
    };
    interface HTMLSearchBarElementEventMap {
        "searchChanged": string;
        "searchSubmitted": string;
    }
    interface HTMLSearchBarElement extends Components.SearchBar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSearchBarElementEventMap>(type: K, listener: (this: HTMLSearchBarElement, ev: SearchBarCustomEvent<HTMLSearchBarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSearchBarElementEventMap>(type: K, listener: (this: HTMLSearchBarElement, ev: SearchBarCustomEvent<HTMLSearchBarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSearchBarElement: {
        prototype: HTMLSearchBarElement;
        new (): HTMLSearchBarElement;
    };
    interface HTMLElementTagNameMap {
        "app-button": HTMLAppButtonElement;
        "loading-spinner": HTMLLoadingSpinnerElement;
        "meal-plan-card": HTMLMealPlanCardElement;
        "recipe-card": HTMLRecipeCardElement;
        "search-bar": HTMLSearchBarElement;
    }
}
declare namespace LocalJSX {
    interface AppButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "loading"?: boolean;
        /**
          * @default 'primary'
         */
        "variant"?: ButtonVariant;
    }
    interface LoadingSpinner {
        /**
          * @default 'medium'
         */
        "size"?: SpinnerSize;
    }
    interface MealPlanCard {
        /**
          * @default ''
         */
        "day"?: string;
        "onEditMeal"?: (event: MealPlanCardCustomEvent<MealPlanEvent>) => void;
        "onRemoveMeal"?: (event: MealPlanCardCustomEvent<MealPlanEvent>) => void;
        "onViewMeal"?: (event: MealPlanCardCustomEvent<MealPlanEvent>) => void;
        /**
          * @default ''
         */
        "recipeImage"?: string;
        /**
          * @default ''
         */
        "recipeTitle"?: string;
    }
    interface RecipeCard {
        /**
          * @default ''
         */
        "area"?: string;
        /**
          * @default ''
         */
        "category"?: string;
        /**
          * @default ''
         */
        "image"?: string;
        /**
          * @default false
         */
        "isFavorite"?: boolean;
        "onFavoriteToggled"?: (event: RecipeCardCustomEvent<RecipeCardEvent & { isFavorite: boolean }>) => void;
        "onRecipeSelected"?: (event: RecipeCardCustomEvent<RecipeCardEvent>) => void;
        /**
          * Identifier returned with card events.
          * @default ''
         */
        "recipeId"?: string;
        /**
          * Public HTML attribute remains `title`; the internal name avoids HTMLElement.title collisions.
          * @default ''
         */
        "recipeTitle"?: string;
    }
    interface SearchBar {
        "onSearchChanged"?: (event: SearchBarCustomEvent<string>) => void;
        "onSearchSubmitted"?: (event: SearchBarCustomEvent<string>) => void;
        /**
          * @default 'Search recipes'
         */
        "placeholder"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }

    interface AppButtonAttributes {
        "variant": ButtonVariant;
        "disabled": boolean;
        "loading": boolean;
    }
    interface LoadingSpinnerAttributes {
        "size": SpinnerSize;
    }
    interface MealPlanCardAttributes {
        "day": string;
        "recipeTitle": string;
        "recipeImage": string;
    }
    interface RecipeCardAttributes {
        "recipeId": string;
        "recipeTitle": string;
        "image": string;
        "category": string;
        "area": string;
        "isFavorite": boolean;
    }
    interface SearchBarAttributes {
        "placeholder": string;
        "value": string;
    }

    interface IntrinsicElements {
        "app-button": Omit<AppButton, keyof AppButtonAttributes> & { [K in keyof AppButton & keyof AppButtonAttributes]?: AppButton[K] } & { [K in keyof AppButton & keyof AppButtonAttributes as `attr:${K}`]?: AppButtonAttributes[K] } & { [K in keyof AppButton & keyof AppButtonAttributes as `prop:${K}`]?: AppButton[K] };
        "loading-spinner": Omit<LoadingSpinner, keyof LoadingSpinnerAttributes> & { [K in keyof LoadingSpinner & keyof LoadingSpinnerAttributes]?: LoadingSpinner[K] } & { [K in keyof LoadingSpinner & keyof LoadingSpinnerAttributes as `attr:${K}`]?: LoadingSpinnerAttributes[K] } & { [K in keyof LoadingSpinner & keyof LoadingSpinnerAttributes as `prop:${K}`]?: LoadingSpinner[K] };
        "meal-plan-card": Omit<MealPlanCard, keyof MealPlanCardAttributes> & { [K in keyof MealPlanCard & keyof MealPlanCardAttributes]?: MealPlanCard[K] } & { [K in keyof MealPlanCard & keyof MealPlanCardAttributes as `attr:${K}`]?: MealPlanCardAttributes[K] } & { [K in keyof MealPlanCard & keyof MealPlanCardAttributes as `prop:${K}`]?: MealPlanCard[K] };
        "recipe-card": Omit<RecipeCard, keyof RecipeCardAttributes> & { [K in keyof RecipeCard & keyof RecipeCardAttributes]?: RecipeCard[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `attr:${K}`]?: RecipeCardAttributes[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `prop:${K}`]?: RecipeCard[K] };
        "search-bar": Omit<SearchBar, keyof SearchBarAttributes> & { [K in keyof SearchBar & keyof SearchBarAttributes]?: SearchBar[K] } & { [K in keyof SearchBar & keyof SearchBarAttributes as `attr:${K}`]?: SearchBarAttributes[K] } & { [K in keyof SearchBar & keyof SearchBarAttributes as `prop:${K}`]?: SearchBar[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-button": LocalJSX.IntrinsicElements["app-button"] & JSXBase.HTMLAttributes<HTMLAppButtonElement>;
            "loading-spinner": LocalJSX.IntrinsicElements["loading-spinner"] & JSXBase.HTMLAttributes<HTMLLoadingSpinnerElement>;
            "meal-plan-card": LocalJSX.IntrinsicElements["meal-plan-card"] & JSXBase.HTMLAttributes<HTMLMealPlanCardElement>;
            "recipe-card": LocalJSX.IntrinsicElements["recipe-card"] & JSXBase.HTMLAttributes<HTMLRecipeCardElement>;
            "search-bar": LocalJSX.IntrinsicElements["search-bar"] & JSXBase.HTMLAttributes<HTMLSearchBarElement>;
        }
    }
}
